### PR TITLE
feat(package): Allow multiple projects to be used

### PR DESCRIPTION
**Pull request by mcfedr**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix
[X] New feature
[ ] Other, please explain:

**What changes did you make? (Give an overview)**

Change the `project` config to allow it to accept an array of projects just like the parser does - https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/parser#parseroptionsproject

**Which issue (if any) does this pull request address?**

**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

**Comment by mcfedr** [comment]
To whoever approved the workflows - thanks, and sorry i didnt check the commitlint before i pushed... i think the tests will pass now - this PR (and i think most of the automatic PRs) should build after https://github.com/standard/ts-standard/pull/164 is merged

**Review by Divlo — CHANGES_REQUESTED** [review]
Thank you for your contribution! @mcfedr

Could you please resolve the conflict and add this change to `CHANGELOG.md`, unfortunately, it's not generated automatically yet.

**Review by Divlo — APPROVED** [review]

**Comment by mcfedr** [comment]
I was about to hit the request review button, and the PR is merged right in front of me :)

**Comment by mcfedr** [comment]
@Divlo always seems like a slightly cheeky question are you land your first PR, but do you have a plan for a new release to npm?

**Comment by Divlo** [comment]
> @Divlo always seems like a slightly cheeky question are you land your first PR, but do you have a plan for a new release to npm?

@mcfedr I don't have the right to publish a new version on `npm` for this package.
I opened a PR for a new release proposal: #166, but I'll let @toddbluhm decide to merge it and release a new version, if everything is good to go. :smile:

**Pull request merged**
