### PR TITLE
Process `--version` Flag Directly

### PR DESCRIPTION
**Pull request by lindluni**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[x] Bug fix
[ ] New feature
[ ] Other, please explain:

**What changes did you make? (Give an overview)**

Directly process the `--version` flag as per: #263 

**Which issue (if any) does this pull request address?**

#263 

**Is there anything you'd like reviewers to focus on?**

Processing the version flag directly in the `cli.js` module much like the `eslint` project does: https://github.com/eslint/eslint/blob/main/lib/cli.js#L333

### CODE REVIEW

**Review by Divlo — APPROVED** [review]
LGTM, thanks! :+1:

Could you add a test in `test/cli.js` to avoid regressions in the future?

**Comment by lindluni** [comment]
Hi @Divlo 

I've added the test, thanks for pointing this out! Appreciate the help!

**Review by Divlo — APPROVED** [review]

**Comment by lindluni** [comment]
@Divlo 

Any chance we can get a `12.0.1` tag and publish it to `npm` to pick up this fix?

Thank you for your help with this!

**Comment by Divlo** [comment]
@lindluni 

PR for the release available there: #265.

**Pull request merged**
