### PR TITLE
chore(release): v12.0.2

### LINKED ISSUE #276: Release v12.0.2
Hi @Divlo 

Is it possible to publish a 12.0.2 release to NPM to pick up this change: https://github.com/standard/ts-standard/pull/269

Thank you ❤️

### PR DESCRIPTION
**Pull request by Divlo**
Release v12.0.2. :tada:

Version updated and git tag created thanks to the `npm version` command.
This time, I should not have forgotten to use `git push --follow-tags`. :sweat_smile:

Fixes #276

### CODE REVIEW

**Review by LinusU — APPROVED** [review]
Neat! 👍

**Comment by lindluni** [comment]
Thank you @Divlo 

Are you able to merge this with the approving review? Or do one of the others have to merge this change?

**Comment by Divlo** [comment]
> Thank you @Divlo
> 
> Are you able to merge this with the approving review? Or do one of the others have to merge this change?

I can merge, but can't publish on `npm`.
@LinusU Could you release a new version? Thanks!

**Comment by LinusU** [comment]
Will do! 🚀

**Comment by LinusU** [comment]
It's published ✅

**Pull request merged**
