### PR TITLE
chore(build): allow installing from git to work

### PR DESCRIPTION
**Pull request by mcfedr**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix
[ ] New feature
[X] Other, please explain:

**What changes did you make? (Give an overview)**

Move the `husky install` command to `prepare` - this is the recommended place to put it with newer husky docs.
This means it wont be run when the package is installed, and `pinst` is no longer needed

**Which issue (if any) does this pull request address?**

**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

**Comment by mcfedr** [comment]
@Divlo would be great to stick this in the "upcoming" 11 release as well.

**Review by Divlo — CHANGES_REQUESTED** [review]
> this is the recommended place to put it with newer husky docs.

That's not true.
See: https://typicode.github.io/husky/#/?id=install-1

> if your package is not private and you're publishing it on a registry like npmjs.com, you need to disable postinstall script using pinst. Otherwise, postinstall will run when someone installs your package and result in an error.

In fact, we're publishing this package to npm, so we must use `pinst`. :smile:
Anyway thank you for your PR! @mcfedr

**Comment by mcfedr** [comment]
Oh weird, I looked at https://www.npmjs.com/package/husky - > under usage

**Comment by mcfedr** [comment]
wait - in the npm section - it talks about prepare - https://typicode.github.io/husky/#/?id=install - and also see the comments about prepare in npm doc-  https://docs.npmjs.com/cli/v7/using-npm/scripts#prepare-and-prepublish

Really we if to start changing stuff, I'd remove the dist folder from git and use prepare with tsc

**Comment by Divlo** [comment]
> wait - in the npm section - it talks about prepare - [typicode.github.io/husky/#/?id=install](https://typicode.github.io/husky/#/?id=install) - and also see the comments about prepare in npm doc- [docs.npmjs.com/cli/v7/using-npm/scripts#prepare-and-prepublish](https://docs.npmjs.com/cli/v7/using-npm/scripts#prepare-and-prepublish)
> 
> Really we if to start changing stuff, I'd remove the dist folder from git and use prepare with tsc

I guess it's fine like that, it does the job. :+1:

> Oh weird, I looked at npmjs.com/package/husky - > under usage

Yes, that's how to use `husky` for projects, not for npm packages.

**Pull request closed without merging**
